language: node_js
node_js:
  - '0.10'
before_install:
  - sudo echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - sudo rm -rf /usr/local/phantomjs
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - 'npm install'
  - 'npm install -g bower'
  - 'npm install -g grunt-cli'
  - 'bower install'

script:
 - grunt test
