language: node_js
node_js:
  - '0.10'

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - 'npm install'
  - 'npm install -g bower'
  - 'npm install -g grunt-cli'
  - 'npm install -g selenium-server'
  - 'bower install --config.interactive=false'
  - "selenium > /dev/null &"

script:
 - grunt test-travis
