language: node_js
node_js:
  - '0.10'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - 'npm install'
  - 'npm install -g bower'
  - 'npm install -g grunt-cli'
  - 'bower install'

script:
 - grunt serve > out & # Start the server
 - PID=$! # Save the PID
 - karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=PhantomJS
 - karma start karma-e2e.conf.js --no-auto-watch --single-run --reporters=dots --browsers=PhantomJS
 - sleep 10
 - kill $PID
 - sleep 10