language: node_js
node_js:
  - '0.10'

before_script:
  - "sudo apt-get update"
  - "sudo apt-get install linux-image-generic-lts-raring linux-headers-generic-lts-raring apt-transport-https"
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys"
  - "sudo sh -c 'echo deb https://get.docker.io/ubuntu docker main\ > /etc/apt/sources.list.d/docker.list'"
  - "sudo apt-get update"
  - "sudo apt-get install --force-yes lxc-docker"
  - "sudo service docker start"

script:
 - "sudo docker build -t babitch_client_travis ."
 - "sudo docker run --privileged -it --rm babitch_client_travis test"
