//Fixtures

var Fixtures = {
    games: [{
        "id": 252,
        "blue_score": 10,
        "red_score": 9,
        "composition": [{
            "player_id": 16,
            "id": 1005,
            "team": "red",
            "position": "defense"
        }, {
            "player_id": 8,
            "id": 1006,
            "team": "blue",
            "position": "attack"
        }, {
            "player_id": 9,
            "id": 1007,
            "team": "red",
            "position": "attack"
        }, {
            "player_id": 12,
            "id": 1008,
            "team": "blue",
            "position": "defense"
        }],
        "goals": [{
            "player_id": 12,
            "conceder_id": 12,
            "id": 3969,
            "position": "defense",
            "autogoal": true
        }, {
            "player_id": 9,
            "conceder_id": 12,
            "id": 3970,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 12,
            "id": 3971,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 12,
            "id": 3972,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 16,
            "id": 3973,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 12,
            "conceder_id": 16,
            "id": 3974,
            "position": "defense",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 16,
            "id": 3975,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 12,
            "conceder_id": 16,
            "id": 3976,
            "position": "defense",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 12,
            "id": 3977,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 16,
            "id": 3978,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 12,
            "id": 3979,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 16,
            "id": 3980,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 12,
            "id": 3981,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 16,
            "id": 3982,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 16,
            "conceder_id": 12,
            "id": 3983,
            "position": "defense",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 16,
            "id": 3984,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 12,
            "id": 3985,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 16,
            "conceder_id": 16,
            "id": 3986,
            "position": "defense",
            "autogoal": true
        }, {
            "player_id": 12,
            "conceder_id": 16,
            "id": 3987,
            "position": "defense",
            "autogoal": false
        }]
    }, {
        "id": 251,
        "blue_score": 10,
        "red_score": 3,
        "composition": [{
            "player_id": 12,
            "id": 1001,
            "team": "red",
            "position": "defense"
        }, {
            "player_id": 8,
            "id": 1002,
            "team": "blue",
            "position": "attack"
        }, {
            "player_id": 7,
            "id": 1003,
            "team": "red",
            "position": "attack"
        }, {
            "player_id": 9,
            "id": 1004,
            "team": "blue",
            "position": "defense"
        }],
        "goals": [{
            "player_id": 8,
            "conceder_id": 7,
            "id": 3956,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 7,
            "id": 3957,
            "position": "defense",
            "autogoal": false
        }, {
            "player_id": 12,
            "conceder_id": 9,
            "id": 3958,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 7,
            "id": 3959,
            "position": "defense",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 7,
            "id": 3960,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 7,
            "id": 3961,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 12,
            "conceder_id": 9,
            "id": 3962,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 7,
            "id": 3963,
            "position": "defense",
            "autogoal": false
        }, {
            "player_id": 12,
            "conceder_id": 9,
            "id": 3964,
            "position": "defense",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 12,
            "id": 3965,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 12,
            "id": 3966,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 12,
            "id": 3967,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 12,
            "id": 3968,
            "position": "attack",
            "autogoal": false
        }]
    }, {
        "id": 250,
        "blue_score": 10,
        "red_score": 6,
        "composition": [{
            "player_id": 7,
            "id": 997,
            "team": "red",
            "position": "defense"
        }, {
            "player_id": 9,
            "id": 998,
            "team": "blue",
            "position": "attack"
        }, {
            "player_id": 16,
            "id": 999,
            "team": "red",
            "position": "attack"
        }, {
            "player_id": 8,
            "id": 1000,
            "team": "blue",
            "position": "defense"
        }],
        "goals": [{
            "player_id": 8,
            "conceder_id": 16,
            "id": 3940,
            "position": "defense",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 16,
            "id": 3941,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 16,
            "id": 3942,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 16,
            "id": 3943,
            "position": "defense",
            "autogoal": false
        }, {
            "player_id": 7,
            "conceder_id": 8,
            "id": 3944,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 16,
            "id": 3945,
            "position": "defense",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 8,
            "id": 3946,
            "position": "defense",
            "autogoal": true
        }, {
            "player_id": 9,
            "conceder_id": 16,
            "id": 3947,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 8,
            "id": 3948,
            "position": "defense",
            "autogoal": true
        }, {
            "player_id": 16,
            "conceder_id": 8,
            "id": 3949,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 7,
            "id": 3950,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 16,
            "conceder_id": 8,
            "id": 3951,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 16,
            "conceder_id": 8,
            "id": 3952,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 8,
            "conceder_id": 7,
            "id": 3953,
            "position": "defense",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 7,
            "id": 3954,
            "position": "attack",
            "autogoal": false
        }, {
            "player_id": 9,
            "conceder_id": 7,
            "id": 3955,
            "position": "attack",
            "autogoal": false
        }]
    }],
    players: [{
        "id": 1,
        "name": "Adrien",
        "email": "adrien"
    }, {
        "id": 2,
        "name": "Denis",
        "email": "denis"
    }, {
        "id": 3,
        "name": "Florent",
        "email": "c"
    }, {
        "id": 4,
        "name": "Morgan",
        "email": "b"
    }, {
        "id": 5,
        "name": "Francis",
        "email": "cy"
    }, {
        "id": 6,
        "name": "J\u00e9r\u00e9my",
        "email": "c"
    }, {
        "id": 7,
        "name": "Florent L",
        "email": "fl"
    }, {
        "id": 8,
        "name": "Nicolas C",
        "email": "nc"
    }, {
        "id": 9,
        "name": "Kenny",
        "email": "kenny"
    }, {
        "id": 10,
        "name": "R\u00e9mi",
        "email": "rle"
    }, {
        "id": 11,
        "name": "Marc",
        "email": "marc"
    }, {
        "id": 12,
        "name": "Aurelian",
        "email": "abe"
    }, {
        "id": 13,
        "name": "Antony",
        "email": "ap"
    }, {
        "id": 14,
        "name": "Benjamin",
        "email": "br"
    }, {
        "id": 15,
        "name": "Pierre Thomas",
        "email": "mail"
    }, {
        "id": 16,
        "name": "Gregory",
        "email": "mail"
    }, {
        "id": 17,
        "name": "Jean micheng",
        "email": "jm"
    }, {
        "id": 18,
        "name": "JulienB",
        "email": "Jbes"
    }, {
        "id": 19,
        "name": "Damien Jv",
        "email": "Damien"
    }, {
        "id": 20,
        "name": "stephanie",
        "email": "stephanie"
    }, {
        "id": 21,
        "name": "Nicolas B",
        "email": "nicolas.b"
    }]
};